Fitting result models
ModellingWebLab/WebLab pull request #281
Opened 2020-09-01 10:54 UTC by helenst

Adapted from #241

2020-09-03 20:57 UTC, jonc125 reviewed
I've not gone through all of this yet, but the models and views certainly look to be along the right lines!

2020-09-03 20:57 UTC, jonc125 commented on weblab/fitting/views.py
> +        return reverse('experiments:list') + '?show_fits=true'
This will need to change once we have a proper matrix view for fitting results!

2020-09-03 20:57 UTC, jonc125 commented on weblab/templates/fitting/fittingresultversion_detail.html
> +        {% if perms.create_experiment %}
This should probably change to run_fits?

2020-09-03 20:57 UTC, jonc125 commented on weblab/templates/fitting/fittingresultversion_detail.html
> +        Note: there is a <a href="{% url 'fitting:result:version' fittingresult.id fittingresult.latest_version.id %}">later version of this fitting</a>.
```suggestion
        Note: there is a <a href="{% url 'fitting:result:version' fittingresult.id fittingresult.latest_version.id %}">newer run of this fitting experiment</a>.
```

2020-09-03 20:57 UTC, jonc125 commented on weblab/templates/fitting/fittingresultversion_detail.html
> +        This fitting has not yet finished running, and so no result files are available.
```suggestion
        This fitting experiment has not yet finished running, and so no result files are available.
```

2020-09-03 20:57 UTC, jonc125 commented on weblab/templates/fitting/fittingresultversion_detail.html
> +        {% dataset_options experiment %}
Does this need updating?

2020-09-03 20:57 UTC, jonc125 commented on weblab/templates/fitting/fittingresultversion_detail.html
> +      <span>Overlay a dataset linked to this protocol:</span>
```suggestion
      <span>Overlay a dataset linked to the associated protocol:</span>
```

We could just overlay the directly linked dataset, but I think giving a wider range of options is good.

2020-09-04 05:24 UTC, jonc125 commented on weblab/experiments/processing.py
> +def submit_runnable(runnable, body, user):
This looks good too!

2020-09-04 05:25 UTC, jonc125 commented on weblab/fitting/processing.py
> +    """Submit a Celery task to run a fitting
```suggestion
    """Submit a Celery task to run a fitting experiment
```

2020-09-04 09:33 UTC, jonc125 commented on weblab/fitting/views.py
> +        return reverse('experiments:list') + '?show_fits=true'
Or it could redirect to one of the simpler views from #276 in the interim?

2020-09-04 09:34 UTC, jonc125 reviewed
I've now gone through the rest of the PR; all looking good so far.

2020-09-24 15:24 UTC, jonc125 requested changes
Fitting experiments are still running so I can't compare results yet, but I've found 2 minor issues from what I can see so far.

2020-09-24 15:24 UTC, jonc125 commented on weblab/templates/fitting/fittingresultversion_detail.html
> +
It would be good to have an `&amp; fitting spec: ...` here as well.

2020-09-24 15:24 UTC, jonc125 commented on weblab/templates/fitting/fittingresultversion_detail.html
> +          <a id="rerunExperiment"><img src="{% static 'img/refresh.png' %}" alt="rerun experiment" title="rerun experiment"/></a> <span id="rerunExperimentAction"></span>
The JS action associated with this doesn't work - it tries to do a normal experiment run, not a fitting experiment.

2020-09-25 14:19 UTC, jonc125 commented
I've now played around with the compare view, and deletion, and both work as expected. So apart from the issues noted above this is good to merge. Would you rather fix the issues here or roll them into #290 @helenst ?

2020-09-25 14:22 UTC, helenst commented
Great! I think at this point it'd be easier to roll it all into one :)

2020-09-25 14:49 UTC, jonc125 approved these changes

2020-10-02 10:55 UTC, merged