276 list of fitting results
ModellingWebLab/WebLab pull request #300
Opened 2020-10-12 11:31 UTC by helenst

Fixes #276

2020-10-13 15:01 UTC, jonc125 commented on weblab/templates/datasets/compare_fittings.html
> +{% block content %}
There's a lot of overlap here with the dataset_detail template. Could we make a new dataset_base or similar that both inherit from maybe?

2020-10-15 09:05 UTC, jonc125 requested changes
Looking good. I tweaked some aspects of the display; figured it was easier just to make the changes than put them as review comments. There are just a few minor things to finish off I think.

2020-10-15 09:05 UTC, jonc125 commented on weblab/entities/tests/test_views.py
> +
Similarly to above, can we add some private versions and check the corresponding results aren't included?

2020-10-16 16:12 UTC, jonc125 approved these changes
Just a very minor suggestion!

I was confused at first that the visibility form still wasn't showing for me (hence the extra test added) but killing & restarting my dev server resolved it 🤷‍♂️

2020-10-20 08:40 UTC, helenst commented on weblab/datasets/tests/test_views.py
> +        ).fittingresult
Indeed - have fixed this, and similarly in entity view tests.

2020-10-20 10:06 UTC, merged