Fitting results matrix
ModellingWebLab/WebLab pull request #314
Opened 2020-10-29 14:30 UTC by helenst

Fitting results matrix

* One per fitting spec, with models on rows and datasets on columns
* Javascript adapted to row/column rather than model/protocol so it can generically handle fitting or simulation experiments (and columns need not have versions)
* Click cell goes through to fitting results form (rather than starting an experiment directly, as with the original matrix)

I've removed the old hacky UI elements for showing fittings in a matrix, although the relevant database fields are still in place.

2020-10-29 17:01 UTC, jonc125 requested changes
Just been having a quick play and had a couple of ideas for improvement; I'll look through properly tomorrow.

1. It would be good to restrict the columns so they only show datasets linked to protocols that are linked to the fitting specification. Otherwise you get potentially many blank cells, and clicking on them leads to a fitting setup page that's "stuck" as the pre-selections aren't actually allowed!
2. The matrix page should link back to the fitting specification - perhaps in the title where its name is mentioned?

2020-10-30 16:19 UTC, jonc125 approved these changes
I've made a few minor suggestions, but overall I'm very happy with this - it seems to work well. So will be good to get some user feedback once deployed :)  I wonder if we should remove the 'fixes' keyword in the description before merging this so the original issue remains open to capture feedback from Michael & Gary there?

2020-10-30 16:19 UTC, jonc125 commented on weblab/fitting/tests/test_views.py
> +        assert response.status_code == 200
```suggestion
```
Would this be a sensible reduction in number of tests?

2020-10-30 16:19 UTC, jonc125 commented on weblab/fitting/tests/test_views.py
> +        assert 'getMatrix' in data
Isn't this redundant with `test_matrix_json` below?

2020-10-30 16:19 UTC, jonc125 commented on weblab/fitting/tests/test_views.py
> +        assert len(columns) == 1
Maybe make this the third assert so it's easier to see why it fails if it does?

2020-10-30 16:19 UTC, jonc125 commented on weblab/fitting/tests/test_views.py
> +        helpers.add_version(related_protocol, visibility='public')
We can probably get away with `add_fake_version` here (and most/all places below?) to make the tests faster.

2020-11-02 13:49 UTC, helenst commented
OK - I've fixed the points you raised and removed the 'fixes' keyword @jonc125

2020-11-03 14:23 UTC, merged